name: test-run
on:
  push:
    paths:
      - 'src/gatling/**'
  schedule:
    - cron: '0 7 * * 1-5'
jobs:
  performance-test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew gatlingRun
      - name: 'Gatling test result'
        uses: actions/upload-artifact@v2
        with:
          name: gatling-test-result
          path: build/reports/gatling
          retention-days: 1