name: Gatling test run
on: [push]
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - run: ./gradlew build
      - run: ./gradlew gatlingRun
      - name: 'Gatling test result'
        uses: actions/upload-artifact@v2
        with:
          name: gatling-test-result
          path: build/reports/gatling