name: gatling-test-run
on:
  push:
    paths:
      - 'src/gatling/**'
  schedule:
    - cron: '0 7 * * 1,4'
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew gatlingRun --all
      - name: 'Gatling test result'
        uses: actions/upload-artifact@v4
        with:
          name: gatling-test-result
          path: build/reports/gatling
          retention-days: 3